### ISSUE TITLE
windows driver kit

### ISSUE THREAD

**Issue by nikitashhh** [madduci/docker-msvc-cpp#10]
Is that possible to add WDK to this docker container? Thanks in advance.

**Comment by madduci** [comment]
Hi

Thanks for the inquiry.

Actually it would be possible by modifying the Powershell script in the
vagrant folder and then copying the necessary files in the docker image.

Do you have/know any open source project I can try with it?



Il mar 22 feb 2022, 20:05 NIKITA ***@***.***> ha scritto:

**Comment by nikitashhh** [comment]
Hi, thanks for the reply.
You can try compile a [TitanHide's driver](https://github.com/mrexodia/TitanHide/tree/master/TitanHide), but I haven't done it, therefore I can't tell is it compiliable on MSVC 16. Also, I have uploaded an [empty driver CMake project](https://github.com/sccoouut/empty_driver), which is compaliable, you can to compile it via WDK. My project has one warning during the compilation, so don't worry about it.

**Comment by madduci** [comment]
Hi @sccoouut 

according to [this site](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#desktop-development-with-c), the Windows Driver Kit can't be installed with the Visual Studio setup in a headless way, which is the procedure I use to build this image.

And according to this [other site](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk), the WDK requires the Windows 11 SDK, which isn't yet supported with Wine.

**Comment by nikitashhh** [comment]
> Hi @sccoouut
> 
> according to [this site](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#desktop-development-with-c), the Windows Driver Kit can't be installed with the Visual Studio setup in a headless way, which is the procedure I use to build this image.

Yeah, it's true, unfortunately it only has its own installation executable.

> And according to this [other site](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk), the WDK requires the Windows 11 SDK, which isn't yet supported with Wine.

[On this site](https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads) it's possible to download older versions of WDK, which are supported on W10SDK too, for example, [WDK for Windows 10, version 2004](https://go.microsoft.com/fwlink/?linkid=2128854).

Thank you for your answer, and for all your work.

**Comment by madduci** [comment]
closing because there's no way to get it working in this image
