### ISSUE TITLE
winehq-stable : Depends: wine-stable

### ISSUE THREAD

**Issue by ulrichard** [madduci/docker-msvc-cpp#2]
When trying to build the base docker, I get this error:

```
The following packages have unmet dependencies:
 winehq-stable : Depends: wine-stable (= 5.0.0~bionic)
E: Unable to correct problems, you have held broken packages.
```
Adding wine-stable-amd64 didn't help.

The behaviro is the same on Ubuntu 18.04 and 16.04

**Comment by madduci** [comment]
Hi

thanks for pointing this out. Wine 5.0 requires SDL as stated in this article. I moved the image to Ubuntu 19.10 and it works.

See here please:
https://tecadmin.net/install-wine-on-ubuntu/
