### ISSUE TITLE
Adding Git to the toolchain

### ISSUE THREAD

**Issue by bram-nijenkamp** [madduci/docker-msvc-cpp#3]
I love your work! However, Might I suggest adding git to the toolchain since git is integrated a lot in modern CmakeLists. That is at least in mine.

**Comment by madduci** [comment]
Hi @FrozenSource 

thanks for interest. I will try to do my best, hoping that the git windows client can work under wine. Never tried it so far.

**Comment by bilke** [comment]
@madduci Have you tried running the git windows client in wine? I tried but failed:

- Just downloaded the portabl version of Git for Windows
- Running `git --version` is fine
- But running e.g. `git clone` produces these errors:

```
Cloning into 'foo'...

abnormal program termination
BUG: compat/mingw.c:138: err_win_to_posix() called without an error!
```

**Comment by madduci** [comment]
@bilke thanks for the effort, but i think it simply cannot work.

I believe it has to do with handling of https / ssh connections. Unfortunately in wine the certificate handling is only partly implemented as a stub, therefore it causes errors.

 The unique possibility I see is to use git externally and mount the required sources in the docker container.

**Comment by bram-nijenkamp** [comment]
That’s a bummer as I would want to use it with cmake 16 functionality (FetchContent). I guess I would need to work around it for windows then….
