### ISSUE TITLE
Connection refused when building dockerfile

### ISSUE THREAD

**Issue by posutsai** [madduci/docker-msvc-cpp#5]
Hi, thanks for your great job. I am trying to build my own docker image based on "msvc-cpp/dockerfile". However, curl can't download zip files from "http://172.17.0.1:20000". Do I need any authentication or the ip has changed?

**Comment by madduci** [comment]
Hi

Thank you for the feedback. Have you run the bash script that's in the
repository? It will start the docker-compose process to start a local
python server to serve elements on the port :2000, served over the host
network.

Unfortunately the build environment differs strongly from the run one, so
the name of the python service can't be used.

Can you try to see what's the mapping of "host.docker.internal" for you?

**Comment by posutsai** [comment]
Sorry for not following the manual step by step. The truth is that when I execute `download-tools.sh` error message shows that the box is not supported. Therefore I try to download the zip file myself. Following is the exact error message after download-tools.sh.

```
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:221:in `add_from_metadata': The box you're attempting to add doesn't support the provider (Vagrant::Errors::BoxAddNoMatchingProvider)
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: StefanScherer/windows_10
Address: https://vagrantcloud.com/StefanScherer/windows_10
Requested provider: [:libvirt]
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: StefanScherer/windows_10
Address: https://vagrantcloud.com/StefanScherer/windows_10
Requested provider: [:libvirt]
```

**Comment by madduci** [comment]
I understand.

From the error, it looks like you don't have VirtualBox installed and
Vagrant is complaining.

If you want to use libvirt instead of VirtualBox, you need a
libvirt-compatible Box to download the tools.

Or alternatively, you can run the provided Powershell provisioning script
to one of your Windows (Virtual-)Machine to get the zipped files.

Afterwards, you can build the docker image.

You can download the latest image (built yesterday) from hub.docker.com
anyways

Il mer 8 set 2021, 16:07 posutsai ***@***.***> ha scritto:

**Comment by posutsai** [comment]
Thanks for your quick response. I would like to try the [image](https://hub.docker.com/r/madduci/docker-wine-msvc/tags?page=1&ordering=last_updated) from dockerhub as well. My windows executable depends on a library that requires GUI interaction, clicking buttons, to complete installation. To do that, I can only forward x11 out of container to my local machine. However, after several attempts, I can only forward x11 successfully with root user.
```
docker run -it --rm -u root -e DISPLAY=$DISPLAY -v $HOME/.Xauthority:/root/.Xauthority  --network=host madduci/docker-wine-msvc:16.11-2019
```
Do you have any suggestion to use command like `$ wine install-deps.exe` with user `wine` in docker container? Or, how to forward x11 under user `wine`?

Thank you.

**Comment by madduci** [comment]
Unfortunately I've never had the opportunity to investigate such a problem,
so I cannot really help in this case :-(

A good starting point could be the wine forum.

But remember that the image is completely headless and you don't have
access to GUI tools, but only to command line ones (in fact, there isn't
any GUI software inside the image at all, just the compiler toolchain)
