### ISSUE TITLE
About vagrant

### ISSUE THREAD

**Issue by bhack** [madduci/docker-msvc-cpp#6]
Have you checked:

https://github.com/mstorsjo/msvc-wine/

Is that one going to install msvc without vagrant?

**Comment by madduci** [comment]
hi @bhack 

thanks for the link, I didn't know this project existed. It looks like it uses Python to download MSVC, instead of booting up a whole Vagrant box

**Comment by bhack** [comment]
I think that buildtools 2019 Is also available in winetricks:
https://github.com/Winetricks/winetricks/blob/master/src/winetricks
