### ISSUE TITLE
x86 build

### ISSUE THREAD

**Issue by MinimaJack** [madduci/docker-msvc-cpp#8]
Need help 
How can i compile for x86 machine?

**Comment by madduci** [comment]
Hi

as I mentioned in my README.md file:

> It has been noticed that on some code, the 32 Bit compiler triggers internal compiler errors (like C1001), especially when dealing with some Windows-specific header file, such as ATL/MFC related code. The 32 Bit compiler is therefore not enabled. On a 64 Bit build, those problems don't appear and the build works fine. It seems that some compiler flags are also affecting those 32 Bit builds.

If you need to enable x86 compilation, you'll have to create a `x86.bat` entrypoint file that has the path to the 32 bit libraries and change the w64-entrypoint.sh to use this file.

**Comment by MinimaJack** [comment]
solved the problem by moving the environment to the conan profile
Thank you!
```
[env]
CONAN_CMAKE_GENERATOR=Ninja
CXX=cl.exe
AR=lib.exe
LIB=C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x86;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\lib\x86;C:\Tools\SDK\10\lib\10.0.18362.0\ucrt\x86;C:\Tools\SDK\10\lib\10.0.18362.0\um\x86
LIBPATH=C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x86;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\lib\x86;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\lib\x86\store\references;C:\Tools\SDK\10\UnionMetadata\10.0.18362.0;C:\Tools\SDK\10\References\10.0.18362.0;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x86;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\lib\x86;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\lib\x86\store\references;C:\Tools\SDK\10\UnionMetadata\10.0.18362.0;C:\Tools\SDK\10\References\10.0.18362.0;
PATH=C:\Tools\Conan\conan;C:\Tools\CMake\bin;C:\Tools\Wix;C:\Tools\Ninja;C:\Tools\VS2019\VC\Tools\MSVC\14.29.30133\bin\HostX64\x86;C:\Tools\SDK\10\bin\10.0.18362.0\x86;C:\Tools\SDK\10\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
VSCMD_ARG_TGT_ARCH=x86
```
